# 1. Create a 3x3x3 array with random values 

In [17]:
import numpy as np
import sys

In [13]:
b = np.random.random((3,3,3))
print(b)

[[[0.2717869  0.20931496 0.87950592]
  [0.27007947 0.32868142 0.63521225]
  [0.20816766 0.89211813 0.04211063]]

 [[0.81386997 0.83658212 0.14495486]
  [0.54239228 0.20933525 0.08243857]
  [0.20246318 0.22719348 0.83719349]]

 [[0.12261811 0.02588046 0.56478964]
  [0.85007815 0.73025066 0.02603564]
  [0.35096239 0.75595518 0.49465582]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
a = np.diag([1, 2, 3, 4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [15]:
a = np.ones((3,3))
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [16]:
y= np.random.random((5,5))
print("Before Normalize:")
print(y)
ymax, ymin = y.max(), y.min()
y = (y - ymin)/(ymax - ymin)
print("After normalize:")
print(y)

Before Normalize:
[[0.30248057 0.16594019 0.27119003 0.7036491  0.07750695]
 [0.49234448 0.01216328 0.84435142 0.32536597 0.6123907 ]
 [0.02139443 0.52846704 0.85336183 0.06038605 0.4458169 ]
 [0.57310974 0.82332262 0.66986769 0.18999955 0.51477829]
 [0.57405096 0.38725326 0.72716612 0.77472013 0.83973147]]
After normalize:
[[0.34512338 0.18280691 0.30792581 0.8220245  0.07767925]
 [0.5708298  0.         0.9892886  0.37232909 0.71353834]
 [0.0109738  0.61377157 1.         0.05732627 0.51551874]
 [0.66684192 0.96428999 0.78186583 0.21140819 0.59749867]
 [0.66796083 0.44589945 0.84998106 0.90651232 0.98379649]]


# 5.  How to find common values between two arrays?

In [18]:
a = np.array([10,22,53,56,66,98])
print("a: ",a)
b = [11,53,1,56]
print("b: ",b)
print("Common values between array a and b :")
print(np.intersect1d(a, b))


a:  [10 22 53 56 66 98]
b:  [11, 53, 1, 56]
Common values between array a and b :
[53 56]


# 6.How to get the dates of yesterday, today and tomorrow?

In [19]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [7]:
a = np.random.randint(0,3,8)
print("First array:")
print(a)
b =  np.random.randint(0,3,8)
print("First array:")
print(b)
print("Check weather above two array are equal or not: ")
q=np.allclose(a,b)
print(q)


First array:
[2 0 1 0 0 1 1 1]
First array:
[0 2 1 2 2 0 1 1]
Check weather above two array are equal or not: 
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [16]:
a=np.random.random(10)
print("Vector: \n",a)

a[a.argmax()]=0
print("Max value replaced by 0 is:\n",a)

Vector: 
 [0.39287401 0.94013531 0.30661733 0.86681148 0.58802166 0.00131435
 0.6534446  0.70163126 0.7926106  0.29853103]
Max value replaced by 0 is:
 [0.39287401 0.         0.30661733 0.86681148 0.58802166 0.00131435
 0.6534446  0.70163126 0.7926106  0.29853103]


# 9. How to print all the values of an array?

In [20]:
a=np.arange(30)
np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


# 10.Subtract the mean of each row of a matrix

In [22]:
print("Original matrix:\n")
X = np.random.rand(4, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.45122161 0.79069048 0.31536506 0.14508491 0.55155578]
 [0.12560934 0.97777915 0.27171226 0.97695862 0.14137434]
 [0.43868559 0.22896103 0.97107737 0.97091336 0.82730738]
 [0.93089355 0.72001185 0.50501808 0.54963322 0.37930294]]

Subtract the mean of each row of the said matrix:

[[ 4.38040861e-04  3.39906912e-01 -1.35418504e-01 -3.05698658e-01
   1.00772210e-01]
 [-3.73077399e-01  4.79092406e-01 -2.26974484e-01  4.78271881e-01
  -3.57312404e-01]
 [-2.48703359e-01 -4.58427913e-01  2.83688420e-01  2.83524415e-01
   1.39918437e-01]
 [ 3.13921620e-01  1.03039923e-01 -1.11953851e-01 -6.73387053e-02
  -2.37668986e-01]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [23]:
a= np.ones(5)
print("a=",a)
b=np.random.randint(0,len(a),10)
print("b=",b)

a= [1. 1. 1. 1. 1.]
b= [1 4 1 1 1 3 0 3 0 0]


In [24]:
a +=np.bincount(b,minlength=len(a))
print(a)

[4. 5. 1. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [29]:
a= np.arange(9).reshape(3,3)
print("a=\n",a)

b= np.arange(9).reshape(3,3)
print("b=\n",b)
c=np.diag(a.dot(b))
print("c=\n",c)

a=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
c=
 [ 15  54 111]


# 13.How to find the most frequent value in an array?

In [31]:
a = np.random.randint(0, 10, 40)
print("Given array:")
print(a)
print("Most frequent value in the above array:")
print(np.bincount(a).argmax())

Given array:
[7 5 5 6 6 3 6 1 5 9 7 7 8 0 6 9 1 3 1 6 0 9 4 3 4 1 4 3 0 5 1 9 3 8 0 5 0
 1 9 6]
Most frequent value in the above array:
1


# 14.How to get the n largest values of an array

In [36]:
a = np.arange(15)
print("Original array:")
print(a)
np.random.shuffle(a)
n = 1
print (a[np.argsort(a)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14]


# 15.How to create a record array from a regular array?

In [40]:
a =np.array(['sklearn','numpy','pandas'])
b=np.array([98,56,12])
c=np.array(['q','r','s'])
results=np.core.records.fromarrays([a,b,c])

In [41]:
print(result[0])
print(result[1])
print(result[2])

('sklearn', 98, 'q')
('numpy', 56, 'r')
('pandas', 12, 's')
